# Define the ros2_controller to be used
controller_manager:
  ros__parameters:
    update_rate: 100

    # This controller is necessary to read the joints' variables
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tricycle_steering_controller:
      type: tricycle_steering_controller/TricycleSteeringController

tricycle_steering_controller:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false

    use_stamped_vel: true   # /tricycle_steering_controller/reference -> geometry_msgs/msg/TwistStamped 
    #use_stamped_vel: false  # /tricycle_steering_controller/reference_unstamped -> geometry_msgs/msg/Twist

    rear_wheels_names: [joint_left_rear_wheel, joint_right_rear_wheel]
    front_wheels_names: [master_joint]

    wheelbase: 0.37266  
    wheel_track: 0.4303  

    front_wheels_radius: 0.12
    rear_wheels_radius: 0.12

    # Odometry
    odom_frame_id: base_footprint
    base_frame_id: chasis